language: cpp
dist: bionic

addons:
  apt:
    packages: &common-apt-packages
      - python3-pip
      # sfml dependencies
      - libxrandr-dev
      - libudev-dev
      - libopenal-dev
      - libflac-dev
      - libvorbis-dev
      - libgl1-mesa-dev

matrix:
  include:
    - name: "clang-tidy 12"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb https://apt.llvm.org/bionic/ llvm-toolchain-bionic-12 main main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - *common-apt-packages
            - clang-12
            - clang-tidy-12
            - libstdc++-8-dev
      script:
        - CXX=clang++-12 cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
        - travis_wait run-clang-tidy-12.py -q -p . "application" -header-filter=".*/application/.*"

install:
  - python3 -m pip install pip --upgrade
  - python3 -m pip install cmake==3.14.4 ninja==1.9.0.post1 --upgrade --user

before_script:
  - cmake --version
  - ninja --version
  - mkdir _build && cd _build
  - eval "${MATRIX_EVAL}"

script:
  - cmake -DCMAKE_BUILD_TYPE="$BUILD_TYPE" $CMAKE_EXTRA_OPTIONS ..
  - cmake --build . --parallel 2
