name: CI

on: [push, pull_request]

jobs:
  ci:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    env:
      CTEST_OUTPUT_ON_FAILURE: ON
      CTEST_PARALLEL_LEVEL: 2

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: ubuntu-22.04-gcc-12
            os: ubuntu-22.04
            compiler: gcc
            version: "12"

          - name: ubuntu-22.04-clang-14
            os: ubuntu-22.04
            compiler: clang
            version: "14"

          - name: ubuntu-22.04-clang-14-bazel
            os: ubuntu-22.04
            compiler: clang
            version: "14"
            bazel: true

          - name: windows-2022-cl
            os: windows-2022
            cmake-args: -A x64

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install (Linux)
        if: runner.os == 'Linux'
        run: |
          python3 -m pip install pip --upgrade
          python3 -m pip install cmake==3.22.5 ninja==1.9.0.post1 --upgrade

          sudo apt update
          sudo apt-get install -y libxrandr-dev libudev-dev libopenal-dev libflac-dev libvorbis-dev libgl1-mesa-dev

          if [ "${{ matrix.compiler }}" = "gcc" ]; then
            sudo apt-get install -y g++-${{ matrix.version }} g++-${{ matrix.version }}-multilib
            echo "CC=gcc-${{ matrix.version }}" >> $GITHUB_ENV
            echo "CXX=g++-${{ matrix.version }}" >> $GITHUB_ENV
          else
            curl -fsSL https://apt.llvm.org/llvm.sh | sudo bash -s ${{ matrix.version }}
            sudo apt-get install -y clang-tidy-${{ matrix.version }} g++-multilib
            echo "CC=clang-${{ matrix.version }}" >> $GITHUB_ENV
            echo "CXX=clang++-${{ matrix.version }}" >> $GITHUB_ENV
          fi

      - name: Install (Windows)
        if: runner.os == 'Windows'
        run: |
          python -m pip install ninja==1.9.0.post1 --upgrade
          python -m pip install cmake==3.22.5 --upgrade

      - name: Build and test (cmake)
        if: ${{ ! matrix.bazel }}
        run: |
          ninja --version
          cmake --version
          cmake -S . -B build ${{ matrix.cmake-args }}
          cmake --build build
          (cd build && ctest)

      - name: Build (bazel)
        if: matrix.bazel
        run: |
          bazelisk build //...
